name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    
    - name: Build
      run: |
        cargo build --release 2>&1 | tee build.log
        exit ${PIPESTATUS[0]}
      
    - name: Upload build log if failed
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-log
        path: build.log
    
    - name: Run tests
      run: cargo test --verbose
